version: "2"
services:
  apostrophe:
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data/uploads:/app/public/uploads
      - ./data/backups:/app/backups
    environment:
      - APOS_MONGODB_URI=mongodb://mongo:27017/db
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - ./data/db:/data/db
    expose:
      - "27017"


version: '3.7'

networks:
  docker-data_traefik-proxy:
    external: true
  danifoldi-internal:

services:
  danifoldi-web:
    image: ghcr.io/danifoldi/danifoldi.com:{{stable}}
    container_name: danifoldi-web
    restart: always
    networks:
      - docker-data_traefik-proxy
      - danifoldi-internal
    volumes:
      - /opt/docker-data/danifoldi-web:/app/public/uploads
    environment:
        - APOS_MONGODB_URI=mongodb://root:mongodb@danifoldi-mongo:27017/danifoldi
    labels:
      - traefik.enable=true
      - traefik.http.routers.danifoldi-web.rule=Host(`danifoldi.com`) || Host(`www.danifoldi.com`)
      - traefik.http.routers.danifoldi-web.entrypoints=https
      - traefik.http.routers.danifoldi-web.tls.certresolver=cloudflare
      - traefik.http.routers.danifoldi-web.service=danifoldi-web
      - traefik.http.routers.danifoldi-web.middlewares=cloudflare-ip-whitelist
      - traefik.http.services.danifoldi-web.loadbalancer.server.port=3000

  danifoldi-mongo:
    image: mongo:latest
    container_name: danifoldi-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - /opt/docker-data/danifoldi-mongo:/data/db
    networks:
      - danifoldi-internal

  danifoldi-mongoexpress:
    image: mongo-express:latest
    container_name: danifoldi-mongoexpress
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://root:mongodb@danifoldi-mongo:27017/
    networks:
      - danifoldi-internal
      - docker-data_traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.danifoldi-mongoexpress.rule=Host(`mongoexpress.danifoldi.com`)
      - traefik.http.routers.danifoldi-mongoexpress.entrypoints=https
      - traefik.http.routers.danifoldi-mongoexpress.tls.certresolver=cloudflare
      - traefik.http.routers.danifoldi-mongoexpress.service=danifoldi-mongoexpress
      - traefik.http.routers.danifoldi-mongoexpress.middlewares=cloudflare-ip-whitelist
      - traefik.http.services.danifoldi-mongoexpress.loadbalancer.server.port=8081
